### PR TITLE
Providing an easier composer install experience

### PR DESCRIPTION
**Pull request by fcool**
This follows an idea coming from the `kde-overlay`:
Provide a documentation directory, which contains predefined package keyword files, so users can easily symlink or copy files this overlay provide in their own configuration.

### CODE REVIEW

**Comment by r7l** [comment]
I like the idea but i wonder if we should rename the directory. My main reason for it would be that i've not seen Gentoo using uppercase directory names in Portage yet. I would at least use a lower case directory name if not use a different name at all. The directory is not holding any documentation as of yet. It rather contains Portage keyword files and it seems to stay that way for quite a while. Maybe use `keywords` as a name?

**Comment by fcool** [comment]
To be honest: I just followed what I've seen:
https://github.com/gentoo/kde/tree/master/Documentation

Are you sure, that a directory like "keywords" will not be interpreted as package category? Maybe its the uppercase name, maybe its the word "Documentation" which avoids logical collisions... I'm not sure where to find reliable informations which rules exactly apply to the directory structure of an overlay besides the documented folders like `profiles`.

**Comment by r7l** [comment]
In order for a directory to be recognized as a categrory it needs to be set specifically. Otherwise it will just be ignored unless it serves another purpose:

[https://wiki.gentoo.org/wiki//etc/portage/categories](https://wiki.gentoo.org/wiki//etc/portage/categories)

My main reason for objecting this directory is probably a more personal objection to uppercase directories. I try to avoid them usually. Software handles them differently all over the place. Sometimes it's above lower case directories, sometimes mixed in or else.

**Comment by fcool** [comment]
Yay! Thanks a lot.  Today I learned something new. :)

I'm fine with both: lowercase `documentation` or `keywords` - as I'm sharing your assumption, that we won't have much to tell in a documentation directory for an overlay...

Which would you prefer?

**Comment by r7l** [comment]
I would go with `keywords` for now up until it's an issue with Portage itself and i don't really see it anytime soon as Gentoo developers are using `profiles` for anything related to enforcement of Portage settings.

**Comment by fcool** [comment]
I believe, this is now ready to be merged, what do you think?

**Comment by r7l** [comment]
Looks good.

**Pull request merged**
